#!/usr/bin/with-contenv bash

if ! grep -q 'config-v2' /config/nginx/site-confs/default; then
    cp /defaults/default /config/nginx/site-confs
fi

if ! grep -q 'core:archive' /etc/crontabs/abc; then
    printf "  *     1       *       *       *       /usr/bin/php /app/matomo/console core:archive --url=%s > /config/log/matomo/matomo-archive.log 2> /config/log/matomo/matomo-archive-errors.log" "${SITEURL}" >> /etc/crontabs/abc
    mkdir -p /config/log/matomo
fi

symlinks=( \
/app/matomo/config \
/app/matomo/plugins \
/app/matomo/misc \
)

shopt -s globstar dotglob

for i in "${symlinks[@]}"; do
[[ -d /config/www/"$(basename "$i")" && ! -L "$i"  ]] && rm -rf "$i"
[[ ! -d /config/www/"$(basename "$i")" && ! -L "$i"  ]] && mv "$i" /config/www/
[[ -d /config/www/"$(basename "$i")" && ! -L "$i"  ]] && ln -s /config/www/"$(basename "$i")" "$i"
done

shopt -u globstar dotglob

chown -R abc:abc \
    /config

find /app -print0 | xargs -0 -P "$(nproc)" -I {} chown abc:abc {}